os: linux
dist: xenial
language: python
python:
  - "3.7"
  - "3.8"
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
env:
  jobs:
    - PLONE_VERSION=52

before_install:
  - sudo apt-get install -y firefox-geckodriver
  - virtualenv -p `which python` .
  - bin/pip install -r requirements.txt -c constraints_plone$PLONE_VERSION.txt
  - cp test_plone$PLONE_VERSION.cfg buildout.cfg

install:
  - bin/buildout -N -t 3 code-analysis:return-status-codes=True annotate
  - bin/buildout -N -t 3 code-analysis:return-status-codes=True

before_script:
- 'export DISPLAY=:99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
- sleep 3
- firefox -v

script:
  - bin/code-analysis
  - bin/test

after_success:
  - bin/createcoverage
  - pip install coverage==3.7 coveralls
  - coveralls
